name: Telegram Answer Bot
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:

  setup:
    runs-on: ubuntu-latest   
    steps:  
    
    - uses: actions/checkout@v3
    
    - name: Set up Python   
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

  install:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

    - name: Install requirements
      run: |
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt
        else
          pip install wheel
          pip install setuptools
          pip install pytest
        fi
        
  run_bot:
  
    needs: install     
    runs-on: ubuntu-latest

    steps:
    
    - name: Run bot
      env:
        BOT_TOKEN: ${{secrets.BOT_TOKEN}} 
        GROUP_CHAT_ID: ${{secrets.GROUP_CHAT_ID}}  
      run: python telegram_bot_otvet_v2.py
