#name: Telegram Bot

#on:
#  schedule:
#   - cron: '*/5 * * * *'

#  workflow_dispatch:

# Налаштування обмеження одночасних запусків   
#concurrency: 
#  group: ${{ github.workflow }}
#  cancel-in-progress: true

#jobs:

#  setup:
  
#    runs-on: ubuntu-latest

 #   steps:
    
 #   - uses: actions/checkout@v3

 # run-bot:

#    needs: setup
    
#    runs-on: ubuntu-latest
    
 #   steps:
    
 #   - name: Install requirements  
 #     run: pip install -r requirements.txt
      
 #   - name: Run bot
 #     env:
 #       BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  
  #    run: python bot.py
