name: Telegram Bot Robota K

on:
  schedule:
   - cron: '*/5 * * * *'

  workflow_dispatch:

# Налаштування обмеження одночасних запусків   
concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:

  setup:
  
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3

  run-bot:

    needs: setup
    
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Install requirements  
      run: pip install pyTelegramBotAPI==4.8.0
      
    - name: Run bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        GROUP_CHAT_ID: ${{ secrets.GROUP_CHAT_ID }}
      run: python bot_otv.py
