
name: Telegram Bot

on:
  schedule:
    - cron: '*/5 * * * *'

  workflow_dispatch:

  # Обмеження одночасних запусків
  concurrency:
    group: ${{ github.workflow }}  
    cancel-in-progress: true 

jobs:

  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

  # Перевірка успішності  
  run-bot:
    needs: setup
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    runs-on: ubuntu-latest

    steps:

    - name: Run bot
      run: python bot.py
